name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Pester
      shell: pwsh
      run: Install-Module Pester -Force
    - name: Run Pester Tests
      shell: pwsh
      run: |
        $TestResults = Invoke-Pester -OutputFile TestResults.xml -OutputFormat NUnitXml -PassThru
        if ($TestResults.FailedCount -gt 0) {
          exit 1
        } else {
          "We're happy little campers"
        }
    - uses: actions/upload-artifact@master
      with:
        name: Pokemon
        path: .
